/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Tender__factory } from "./Tender__factory";
export { TenderManager__factory } from "./TenderManager__factory";
