/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Tender } from "./Tender";
export type { TenderManager } from "./TenderManager";
export * as factories from "./factories";
export { Tender__factory } from "./factories/Tender__factory";
export { TenderManager__factory } from "./factories/TenderManager__factory";
